### ISSUE TITLE
[Suggestion] Wind Charge Effect should be separate when player deploys it to itself.

### ISSUE THREAD

**Issue by makumaku1974** [CreativeMD/EnhancedVisuals#143]
Wind Charge for the player should have a different effect.

If Wind Charge is deployed by the player, it shouldn't cause blur to the players FOV. This should only affect when it is deployed from the Breeze, Dispensers, and other Players.

**Comment by CreativeMD** [comment]
I have disabled the explosion effect for the wind charge, because I think this is way too annoying. Would that fix your issue as well?

**Comment by makumaku1974** [comment]
Is it on the latest update for 1.21? If it is then good God i've waited for so long. 
Breeze should i guess have something customized instead of ignored.

**Comment by CreativeMD** [comment]
Yes it is out already.
Do you have any suggestion for an effect for the Breeze?

**Comment by makumaku1974** [comment]
> Yes it is out already. Do you have any suggestion for an effect for the Breeze?

Just dont blur it... Because in Wind Charge it still affects me btw. Like the item.
![image](https://github.com/user-attachments/assets/15a2d7bf-12d3-4605-aaf8-7dd41b2debab)

**Comment by makumaku1974** [comment]
Btw it is still affecting me. Can you perhaps show yours?

![image](https://github.com/user-attachments/assets/246381e4-da94-4044-b7d0-ba7366d8781c)

**Comment by CreativeMD** [comment]
If you use the command /cmdclientconfig and then go to enhancedvisuals -> general -> handlers -> explosion. Check if ignoreBreeze and ignoreMace are both set to true.

**Comment by makumaku1974** [comment]
![image](https://github.com/user-attachments/assets/9f4931a4-9ec0-47fc-ac57-e550d749795e)

**Comment by makumaku1974** [comment]
imma delete my config then try again

ps: still dont work.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Turns out there was a problem with fabric. Thanks for reporting this issue and spending the time to figure out a solution!

**Comment by makumaku1974** [comment]
> Fixed in the newest version. Turns out there was a problem with fabric. Thanks for reporting this issue and spending the time to figure out a solution!

there is still a problem... the "player" itself when using Wind Charge.

Also what I mean about the Breeze is that i'll be okay keeping the Breeze be annoying but the "player" using wind charge should remove. But that should be a config option to ignorePlayer i hope.

**Comment by CreativeMD** [comment]
> there is still a problem... the "player" itself when using Wind Charge.

What exactly do you mean with that?
> Also what I mean about the Breeze is that i'll be okay keeping the Breeze be annoying but the "player" using wind charge should remove. But that should be a config option to ignorePlayer i hope.

You mean when the player shots a wind charge?

Sorry for responding that late.

**Comment by makumaku1974** [comment]
> > there is still a problem... the "player" itself when using Wind Charge.
> 
> What exactly do you mean with that?
> 
> > Also what I mean about the Breeze is that i'll be okay keeping the Breeze be annoying but the "player" using wind charge should remove. But that should be a config option to ignorePlayer i hope.
> 
> You mean when the player shots a wind charge?
> 
> Sorry for responding that late.

The player shooting a wind charge to itself basically still gets blurry.

**Comment by makumaku1974** [comment]
It's actually okay that when Breeze shoots a wind charge on players, the players get tinnitus and blur vision.

**Comment by CreativeMD** [comment]
Added an option for the wind charge as well. You can configure whether a wind charge from a breeze should cause this effect. Use the command /cmdclientconfig -> enhancedvisuals -> handler -> explosion to see options.
