### ISSUE TITLE
In certain server scenarios without the EnhancedVisuals Mod installed, client-side configurations disabling deathMessages may not take effect.

### ISSUE THREAD

**Issue by MapleSugar365** [CreativeMD/EnhancedVisuals#185]
Reproduction Steps:  
1. The server does not have the EnhancedVisuals Mod installed.  
2. The client sets the deathMessages enable option to false in the local enhancedvisuals.json file.  
3. After launching the client, directly join the server. When dying in Survival mode, the deathMessages will still appear on the respawn screen.  
(Reproduction key point: After launching the client, do not first enter a single-player world and return to the main menu before joining the server; otherwise, the issue will not be reproducible.)

mc1.21.1
neoforge21.1.187
EnhancedVisuals_NEOFORGE_v1.8.21_mc1.21.1

**Comment by CreativeMD** [comment]
Sorry, but this issue will not be fixed. Currently there is no good way to determine whether a mod is installed on server side or not. If the client does not receive any configuration it will simply reset to the default. Making it load your client side configuration would require knowledge that this mod is not installed. Please install EnhancedVisuals on server side. The mod does not really work without the server anyway.

**Comment by MapleSugar365** [comment]
> Sorry, but this issue will not be fixed. Currently there is no good way to determine whether a mod is installed on server side or not. If the client does not receive any configuration it will simply reset to the default. Making it load your client side configuration would require knowledge that this mod is not installed. Please install EnhancedVisuals on server side. The mod does not really work without the server anyway.

Hello, I believe that even without receiving the relevant configuration file for the server's EnhancedVisuals, it should use the client's local configuration parameters instead of hard-coded simple reversion to default settings. Currently, even if EnhancedVisuals is not installed on the server, its visual effects can still display properly. As you know, for servers, fewer mods mean fewer issues.

**Comment by CreativeMD** [comment]
Problem is that CreativeCore syncs all configuration and it only sends the changes from the default configuration. If no changes are received default configuration will be used, which is the case almost all the time. In order to make it work I would have to implement a fallback system which checks if a mod is installed on server side if not it has to be excluded from normal configuration synchronization. In my eyes that is too much work for something very small. I know this might be frustrating for you, but I sometimes I have to cut corners, because my time is limited. Maybe in the future it will be fixed, but it would require some more thought process and changes to the configuration of CreativeCore.

**Comment by MapleSugar365** [comment]
> Problem is that CreativeCore syncs all configuration and it only sends the changes from the default configuration. If no changes are received default configuration will be used, which is the case almost all the time. In order to make it work I would have to implement a fallback system which checks if a mod is installed on server side if not it has to be excluded from normal configuration synchronization. In my eyes that is too much work for something very small. I know this might be frustrating for you, but I sometimes I have to cut corners, because my time is limited. Maybe in the future it will be fixed, but it would require some more thought process and changes to the configuration of CreativeCore.

Alright bro, I've reviewed your source code and I get it—this is indeed a significant change. Please fix other issues like #184. I'll fork a repository copy to change the default enabled death messages to false.

Thanks !

**Comment by CreativeMD** [comment]
Other issue has been fixed a few minutes ago.

**Comment by MapleSugar365** [comment]
> Other issue has been fixed a few minutes ago.

If I'm disturbing you, I apologize for that. Using EnhancedVisuals_NEOFORGE_v1.8.22_mc1.21.1, #184 , this issue still hasn't been fixed—my screen still doesn't blur when I'm thirsty. I’ve confirmed that I’m on the latest version.

**Comment by CreativeMD** [comment]
Replied you over there.
