### ISSUE TITLE
[1.15.2]Ghast Fireball causes server crash

### ISSUE THREAD

**Issue by mcfensi** [CreativeMD/EnhancedVisuals#45]
1.Ghast Fireball causes server crash。

2.If the server does not have this mod installed, you will not be able to enter the server

**Comment by CreativeMD** [comment]
Can you send me the crash?

2. Makes sense because you need it on the server.

**Comment by mcfensi** [comment]
[crash-2020-03-28_21.47.34-server.txt](https://github.com/CreativeMD/EnhancedVisuals/files/4397254/crash-2020-03-28_21.47.34-server.txt)

**Comment by CreativeMD** [comment]
It's fixed in the newest version. Thank you very much for your help!

**Comment by mcfensi** [comment]
I used the latest 1.3.7 version, but it still crashes in the server. If single player is used, the game will crash.
[crash-2020-03-29_10.56.59-server.txt](https://github.com/CreativeMD/EnhancedVisuals/files/4398231/crash-2020-03-29_10.56.59-server.txt)
[crash-2020-03-29_11.06.41-server.txt](https://github.com/CreativeMD/EnhancedVisuals/files/4398232/crash-2020-03-29_11.06.41-server.txt)

**Comment by CreativeMD** [comment]
Oh right, made a mistake can you try out v1.3.8?

**Comment by mcfensi** [comment]
I didn't find 1.3.8, if you send me, I can try

**Comment by mcfensi** [comment]
I see it, I'm going to test it now

**Comment by mcfensi** [comment]
OK, 1.3.8 is no longer a problem.

**Comment by CreativeMD** [comment]
nice perfect!

**Comment by Alaberti** [comment]
Will this fix be ported to the 1.14.4 version? This issue is also present there. Please and thank you?

**Comment by CreativeMD** [comment]
@Alaberti sorry I have abandoned 1.14 already, I won't do any fixes for that version.
